name: Windows tests
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Run synthetic tests
        shell: pwsh
        run: |
          ./tests/Run-Tests.ps1
          ./tests/Workflow-Tests.ps1
          ./tests/Probe-Tests.ps1
          ./tests/Window-Tests.ps1
